# Generated by Django 5.2.6 on 2025-09-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_perfil_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='tipo',
        ),
    ]
