# Generated by Django 5.2.6 on 2025-09-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_perfil_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='adm',
            field=models.BooleanField(default=False),
        ),
    ]
