# Generated by Django 5.2.6 on 2025-09-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_perfil_adm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['nome_completo']},
        ),
    ]
