# Generated by Django 5.2.6 on 2025-09-16 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('titulo', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('status', models.CharField(default='não_iniciado')),
                ('descricao', models.TextField()),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='usuario.perfil')),
            ],
        ),
    ]
