# Generated by Django 5.2.6 on 2025-09-16 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.perfil'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
