# Generated by Django 5.2.6 on 2025-09-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0002_chamado_id_alter_chamado_autor_alter_chamado_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'ordering': ['data']},
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('não_iniciado', 'Não iniciado'), ('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='não_iniciado'),
        ),
    ]
