# Generated by Django 5.2.6 on 2025-09-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0004_alter_chamado_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='nao_iniciado', max_length=20),
        ),
    ]
