# Generated by Django 5.2.6 on 2025-09-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0005_alter_chamado_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'ordering': ['-data']},
        ),
    ]
