# Generated by Django 5.2.6 on 2025-09-18 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0006_alter_chamado_options'),
        ('usuario', '0004_perfil_adm'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='usuario.perfil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chamado',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='usuario.perfil'),
        ),
    ]
