# Generated by Django 5.2.6 on 2025-09-19 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0007_chamado_responsavel_alter_chamado_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='arquivos')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamado', to='chamado.chamado')),
            ],
        ),
    ]
