# Generated by Django 5.2.5 on 2025-09-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0008_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivo', to='chamado.chamado'),
        ),
    ]
